routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\BAAkuisisiController;
use Illuminate\Support\Facades\Route;

Route::post('/signin', 'Api\AuthController@login')->name('signin');

Route::group(['middleware' => ['authenticated']], function () {
    Route::group(['prefix' => 'dashboard'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard.index');
    });

    Route::group(['prefix' => 'daftar-arsip'], function () {
        Route::get('/', 'ArsipController@index')->name('arsip.index');
        Route::post('/store', 'ArsipController@store')->name('arsip.store');
        Route::get('/{id}/show', 'ArsipController@show')->name('arsip.show');
        Route::post('/update/{id}', 'ArsipController@update')->name('arsip.update');
        Route::post('/destroy/{id}', 'ArsipController@destroy')->name('arsip.destroy');
    });

    Route::group(['prefix' => 'audit-trial'], function () {
        Route::get('/', 'AuditTrialController@index')->name('audit-trial.index');
    });

    Route::group(['prefix' => 'group-hak-akses'], function () {
        Route::get('/', 'GroupHakAksesController@index')->name('group-hak-akses.index');
    });

    Route::group(['prefix' => 'group-jabatan'], function () {
        Route::get('/', 'GroupJabatanController@index')->name('group-jabatan.index');
    });

    Route::group(['prefix' => 'instansi'], function () {
        Route::get('/', 'InstansiController@index')->name('instansi.index');
    });

    Route::group(['prefix' => 'jabatan'], function () {
        Route::get('/', 'JabatanController@index')->name('jabatan.index');
        Route::get('/get', 'JabatanController@get')->name('jabatan.get');
        Route::get('/create', 'JabatanController@create')->name('jabatan.create');
        Route::post('/store', 'JabatanController@store')->name('jabatan.store');
        Route::get('/{id}/edit', 'JabatanController@edit')->name('jabatan.edit');
        Route::post('/update/{id}', 'JabatanController@update')->name('jabatan.update');
        Route::post('/delete', 'JabatanController@destroy')->name('jabatan.destroy');
        });



    Route::group(['prefix' => 'jenis-organisasi'], function () {
        Route::get('/', 'JenisOrganisasiController@index')->name('jenis-organisasi.index');

    });

    Route::group(['prefix' => 'pengguna'], function () {
        Route::get('/', 'PenggunaController@index')->name('pengguna.index');
        Route::get('/get', 'PenggunaController@get')->name('pengguna.get');
        Route::get('/create', 'PenggunaController@create')->name('pengguna.create');
        Route::post('/store', 'PenggunaController@store')->name('pengguna.store');
        Route::get('/{id}/edit', 'PenggunaController@edit')->name('pengguna.edit');
        Route::post('/update/{id}', 'PenggunaController@update')->name('pengguna.update');
        Route::post('/delete', 'JabatanController@destroy')->name('pengguna.destroy');
    });

    Route::group(['prefix' => 'referensi-instansi'], function () {
        Route::get('/', 'ReferensiInstansiController@index')->name('referensiinstansi.index');
    });

    Route::group(['prefix' => 'unit-kerja'], function () {
        Route::get('/', 'UnitKerjaController@index')->name('unit-kerja.index');
        Route::get('/get', 'UnitKerjaController@get')->name('unit-kerja.get');
        Route::get('/create', 'UnitKerjaController@create')->name('unit-kerja.create');
        Route::post('/store', 'UnitKerjaController@store')->name('unit-kerja.store');
        Route::get('/{id}/edit', 'UnitKerjaController@edit')->name('unit-kerja.edit');
        Route::post('/update/{id}', 'UnitKerjaController@update')->name('unit-kerja.update');
        Route::post('/delete', 'UnitKerjaController@destroy')->name('unit-kerja.destroy');
    });

//    akuisisi
    Route::prefix('akuisisi')->name('akuisisi.')->group(function () {
        Route::prefix('usul-serah')->name('usul-serah.')->group(function () {
            Route::get('/', 'UsulSerahController@index')->name('index');
            Route::get('/get', 'UsulSerahController@get')->name('get');
            Route::get('/create', 'UsulSerahController@create')->name('create');
            Route::get('/{id}', 'UsulSerahController@show')->name('show');
            Route::post('/store', 'UsulSerahController@store')->name('store');
            Route::post('/update/{id}', 'UsulSerahController@update')->name('update');
            Route::post('/delete', 'UsulSerahController@destroy')->name('destroy');
        });
        Route::prefix('ba-akuisisi')->name('ba-akuisisi.')->group(function () {
            Route::get('/', 'BAAkuisisiController@index')->name('index');
            Route::get('/get', 'BAAkuisisiController@get')->name('get');
            Route::get('/create', 'BAAkuisisiController@create')->name('create');
            Route::get('/{id}', 'BAAkuisisiController@show')->name('show');
            Route::get('/detail/{id}', 'BAAkuisisiController@detail')->name('detail');
            Route::post('/store', 'BAAkuisisiController@store')->name('store');
            Route::post('/update/{id}', 'BAAkuisisiController@update')->name('update');
            Route::post('/delete', 'BAAkuisisiController@destroy')->name('destroy');
        });
        Route::group([], function () {
            Route::get('/', 'AkuisisiController@index')->name('index');
            Route::get('/get', 'AkuisisiController@getList')->name('get');
            Route::get('/create', 'AkuisisiController@create')->name('create');
            Route::get('/{id}', 'AkuisisiController@show')->name('show');
            Route::post('/store', 'AkuisisiController@store')->name('store');
            Route::post('/confirm', 'AkuisisiController@confirm')->name('confirm');
            Route::post('/update/{id}', 'AkuisisiController@update')->name('update');
            Route::post('/delete', 'AkuisisiController@destroy')->name('destroy');
        });
        
    });

//    pengolahan
    Route::prefix('pengolahan')->name('pengolahan.')->group(function () {
        Route::prefix('arsip-statis')->name('arsip-statis.')->group(function () {
            Route::get('/', 'ArsipStatisController@index')->name('index');
            Route::get('/get', 'ArsipStatisController@get')->name('get');
            Route::get('/create', 'ArsipStatisController@create')->name('create');
            Route::get('/{id}', 'ArsipStatisController@show')->name('show');
            Route::post('/store', 'ArsipStatisController@store')->name('store');
            Route::post('/update/{id}', 'ArsipStatisController@update')->name('update');
            Route::post('/delete', 'ArsipStatisController@destroy')->name('destroy');
        });
        Route::group([], function () {
            Route::get('/', 'AkuisisiController@index')->name('index');
            Route::get('/get', 'AkuisisiController@getList')->name('get');
            Route::get('/create', 'AkuisisiController@create')->name('create');
            Route::get('/{id}', 'AkuisisiController@show')->name('show');
            Route::post('/store', 'AkuisisiController@store')->name('store');
            Route::post('/confirm', 'AkuisisiController@confirm')->name('confirm');
            Route::post('/update/{id}', 'AkuisisiController@update')->name('update');
            Route::post('/delete', 'AkuisisiController@destroy')->name('destroy');
        });
    });
});

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

app/Http/Controllers/ArsipStatisController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;

class ArsipStatisController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            (object)[
                'id' => rand(),
                'kode_referensi' => 'IDN-RAB.09.06-15032-XXX-YYY-01',
                'kode_klasifikasi' => 'LK.02',
                'informasi_uraian_arsip' => 'Berkas Pengajuan DUPAK a.n Sahid Triambudi',
                'jumlah_arsip' => '2',
                'akhir_retensi_arsip' => Carbon::now()->subMonth(2)->format('d M Y'),
            ],
            (object)[
                'id' => rand(),
                'kode_referensi' => '',
                'kode_klasifikasi' => 'LK.02',
                'informasi_uraian_arsip' => 'Berkas Pengajuan DUPAK a.n Sahid Triambudi',
                'jumlah_arsip' => '2',
                'akhir_retensi_arsip' => Carbon::now()->subMonth(2)->format('d M Y'),
                
            ],
        ];

        return view('pages.pengolahan.arsip_statis.index', compact(['data']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/pengolahan/arsip_statis/index.blade.php
@extends('layouts.begin_back')

@section('open_pengolahan', 'nav-item-expanded nav-item-open')

@section('pengolahan', 'active')

@section('pengolahan_arsip-statis_index', 'active')

@section('title', 'Arsip Statis')

@section('content')
    <!-- Page header -->
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4>
                <i class="icon-drawer-in mr-2"></i> <span class="font-weight-semibold">Daftar Arsip Statis</span> - List
            </h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        {{--<div class="header-elements d-none text-center text-md-left mb-3 mb-md-0">
            <a href="{{route('akuisisi.arsip-statis.create')}}"
               class="btn bg-teal btn-labeled btn-labeled-left">
                <b><i class="icon-plus2"></i></b> Buat baru
            </a>
        </div>--}}
    </div>
    <!-- /page header -->


    <div class="page-content pt-0">
        <div class="content-wrapper">
            <div class="content">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-header bg-white">
                                <h6 class="card-title">Daftar Arsip Statis</h6>
                            </div>
                            <table class="table datatable-responsive-control-right table-hover table-bordered">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th style="width: 40%">Kode Referensi</th>
                                    <th style="width: 20%">Kode Klasifikasi</th>
                                    <th style="width: 40%">Informasi Uraian Arsip</th>
                                    <th >Jumlah Arsip</th>
                                    <th style="width: 30%">Akhir Retensi Arsip</th>
                                    <th style="width: 20%" class="text-center">Aksi</th>
                                    <th  class="text-center">Status</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody> 
                                @foreach ($data as $key => $item)
                                    <tr>
                                        <td>{{ $key + 1 }}</td>
                                        <td>{{ $item->kode_referensi}}</td>
                                        <td>{{ $item->kode_klasifikasi }}</td>
                                        <td>{{ $item->informasi_uraian_arsip }}</td>
                                        <td>{{ $item->jumlah_arsip }}</td>
                                        <td>{{ $item->akhir_retensi_arsip }}</td>
                                        <td style="white-space: nowrap">
                                            <a href="{{ route('pengolahan.arsip-statis.show', ['id' => $item->id]) }}"
                                               class="list-icons-item text-info btn-icon">
                                                <i class="icon-file-eye"></i>
                                            </a>
                                        </td>
                                        <td class="text-center">
                                            @empty($item->kode_referensi)
                                            <span class="badge badge-secondary">Kode Referensi Belum Ditambahkan</span>
                                            @else
                                            <span class="badge badge-success">Kode Referensi Sudah Ditambahkan</span>
                                            @endempty
                                        </td>
                                        <td></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('addon-script')
    <script src="{{ asset('global_assets/js/plugins/notifications/sweet_alert.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/tables/datatables/extensions/responsive.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/forms/styling/switchery.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/forms/styling/switch.min.js') }}"></script>
@endpush

@section('footer-script')
    <script src="{{ asset('global_assets/js/demo_pages/datatables_responsive.js') }}"></script>
    <script src="{{ asset('global_assets/js/demo_pages/form_checkboxes_radios.js') }}"></script>

    <script>
        $(document).ready(function () {
            $('.datatable-responsive-control-right').on('click', '.delete-item', function (e) {
                var id = $(this).data('id');

                swal.fire({
                    title: 'Hapus BA Akuisisi',
                    text: 'Apakah Anda yakin ingin menghapus BA Akuisisi ini?',
                    type: 'question',
                    showCancelButton: true,
                    confirmButtonText: 'Ya, Hapus!',
                    cancelButtonText: 'Batal!',
                    confirmButtonClass: 'btn btn-danger',
                    cancelButtonClass: 'btn btn-link',
                    buttonsStyling: false
                }).then(function (result) {
                    if (result.value) {
                        $.ajax({
                            method: 'POST',
                            dataType: 'json',
                            url: "{{ route('akuisisi.ba-akuisisi.destroy') }}",
                            data: {
                                "_token": "{{ csrf_token() }}",
                                "id": id,
                            }
                        }).done(function (response) {
                            if (response.status == true) {
                                swal.fire({
                                    title: 'Yeay!',
                                    text: response.message,
                                    type: 'success'
                                });
                                location.reload();
                            } else if (response.status == false) {
                                swal.fire({
                                    title: 'Auch!',
                                    text: response.message,
                                    type: 'error'
                                });
                                location.reload();
                            }
                        })
                    }
                });
            });

            $('.dataTables_length select').select2({
                minimumResultsForSearch: Infinity,
                dropdownAutoWidth: true,
                width: 'auto'
            });
        });

        function initDatatable() {
            $('.datatable-responsive-control-right').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('akuisisi.usul-serah.get') }}",
                columns: [
                    {
                        "data": "nomenklatur_ori"
                    },
                    {
                        "data": "nama"
                    },
                    {
                        "data": "status"
                    },
                    {
                        // "data": 'action',
                        "name": 'action',
                        "orderable": false,
                        "searchable": false
                    },
                    {
                        "data": null,
                        "defaultContent": ""
                    },
                ],
                responsive: {
                    details: {
                        type: 'column',
                        target: -1
                    }
                },
                columnDefs: [
                    {
                        "className": "dt-body-center",
                        "targets": [3],
                        "render": function (data, type, row) {
                            let id = row['id'];
                            return '<a href="/unit-kerja/' + id + '/edit" class="list-icons-item text-info btn-icon">' +
                                '   <i class="icon-pencil"></i>' +
                                '</a>' +
                                '   <a href="#" data-id="' + id + '" class="list-icons-item text-danger btn-icon delete-item">' +
                                '   <i class="icon-trash"></i>' +
                                '</a>';
                        }
                    },
                    {
                        className: 'control',
                        orderable: false,
                        targets: -1
                    },
                    {
                        width: "100px",
                    },
                    {
                        orderable: false,
                    }
                ]
            });
        }
    </script>
@endsection