routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\BAAkuisisiController;
use Illuminate\Support\Facades\Route;

Route::post('/signin', 'Api\AuthController@login')->name('signin');

Route::group(['middleware' => ['authenticated']], function () {
    Route::group(['prefix' => 'dashboard'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard.index');
    });

    Route::group(['prefix' => 'daftar-arsip'], function () {
        Route::get('/', 'ArsipController@index')->name('arsip.index');
        Route::post('/store', 'ArsipController@store')->name('arsip.store');
        Route::get('/{id}/show', 'ArsipController@show')->name('arsip.show');
        Route::post('/update/{id}', 'ArsipController@update')->name('arsip.update');
        Route::post('/destroy/{id}', 'ArsipController@destroy')->name('arsip.destroy');
    });

    Route::group(['prefix' => 'audit-trial'], function () {
        Route::get('/', 'AuditTrialController@index')->name('audit-trial.index');
    });

    Route::group(['prefix' => 'group-hak-akses'], function () {
        Route::get('/', 'GroupHakAksesController@index')->name('group-hak-akses.index');
    });

    Route::group(['prefix' => 'group-jabatan'], function () {
        Route::get('/', 'GroupJabatanController@index')->name('group-jabatan.index');
    });

    Route::group(['prefix' => 'instansi'], function () {
        Route::get('/', 'InstansiController@index')->name('instansi.index');
    });

    Route::group(['prefix' => 'jabatan'], function () {
        Route::get('/', 'JabatanController@index')->name('jabatan.index');
        Route::get('/get', 'JabatanController@get')->name('jabatan.get');
        Route::get('/create', 'JabatanController@create')->name('jabatan.create');
        Route::post('/store', 'JabatanController@store')->name('jabatan.store');
        Route::get('/{id}/edit', 'JabatanController@edit')->name('jabatan.edit');
        Route::post('/update/{id}', 'JabatanController@update')->name('jabatan.update');
        Route::post('/delete', 'JabatanController@destroy')->name('jabatan.destroy');
        });



    Route::group(['prefix' => 'jenis-organisasi'], function () {
        Route::get('/', 'JenisOrganisasiController@index')->name('jenis-organisasi.index');

    });

    Route::group(['prefix' => 'pengguna'], function () {
        Route::get('/', 'PenggunaController@index')->name('pengguna.index');
        Route::get('/get', 'PenggunaController@get')->name('pengguna.get');
        Route::get('/create', 'PenggunaController@create')->name('pengguna.create');
        Route::post('/store', 'PenggunaController@store')->name('pengguna.store');
        Route::get('/{id}/edit', 'PenggunaController@edit')->name('pengguna.edit');
        Route::post('/update/{id}', 'PenggunaController@update')->name('pengguna.update');
        Route::post('/delete', 'JabatanController@destroy')->name('pengguna.destroy');
    });

    Route::group(['prefix' => 'referensi-instansi'], function () {
        Route::get('/', 'ReferensiInstansiController@index')->name('referensiinstansi.index');
    });

    Route::group(['prefix' => 'unit-kerja'], function () {
        Route::get('/', 'UnitKerjaController@index')->name('unit-kerja.index');
        Route::get('/get', 'UnitKerjaController@get')->name('unit-kerja.get');
        Route::get('/create', 'UnitKerjaController@create')->name('unit-kerja.create');
        Route::post('/store', 'UnitKerjaController@store')->name('unit-kerja.store');
        Route::get('/{id}/edit', 'UnitKerjaController@edit')->name('unit-kerja.edit');
        Route::post('/update/{id}', 'UnitKerjaController@update')->name('unit-kerja.update');
        Route::post('/delete', 'UnitKerjaController@destroy')->name('unit-kerja.destroy');
    });

//    akuisisi
    Route::prefix('akuisisi')->name('akuisisi.')->group(function () {
        Route::prefix('usul-serah')->name('usul-serah.')->group(function () {
            Route::get('/', 'UsulSerahController@index')->name('index');
            Route::get('/get', 'UsulSerahController@get')->name('get');
            Route::get('/create', 'UsulSerahController@create')->name('create');
            Route::get('/{id}', 'UsulSerahController@show')->name('show');
            Route::post('/store', 'UsulSerahController@store')->name('store');
            Route::post('/update/{id}', 'UsulSerahController@update')->name('update');
            Route::post('/delete', 'UsulSerahController@destroy')->name('destroy');
        });
        Route::prefix('ba-akuisisi')->name('ba-akuisisi.')->group(function () {
            Route::get('/', 'BAAkuisisiController@index')->name('index');
            Route::get('/get', 'BAAkuisisiController@get')->name('get');
            Route::get('/create', 'BAAkuisisiController@create')->name('create');
            Route::get('/{id}', 'BAAkuisisiController@show')->name('show');
            Route::get('/detail/{id}', 'BAAkuisisiController@detail')->name('detail');
            Route::post('/store', 'BAAkuisisiController@store')->name('store');
            Route::post('/update/{id}', 'BAAkuisisiController@update')->name('update');
            Route::post('/delete', 'BAAkuisisiController@destroy')->name('destroy');
        });
        Route::group([], function () {
            Route::get('/', 'AkuisisiController@index')->name('index');
            Route::get('/get', 'AkuisisiController@getList')->name('get');
            Route::get('/create', 'AkuisisiController@create')->name('create');
            Route::get('/{id}', 'AkuisisiController@show')->name('show');
            Route::post('/store', 'AkuisisiController@store')->name('store');
            Route::post('/confirm', 'AkuisisiController@confirm')->name('confirm');
            Route::post('/update/{id}', 'AkuisisiController@update')->name('update');
            Route::post('/delete', 'AkuisisiController@destroy')->name('destroy');
        });
        
    });

//    pengolahan
    Route::prefix('pengolahan')->name('pengolahan.')->group(function () {
        Route::prefix('arsip-statis')->name('arsip-statis.')->group(function () {
            Route::get('/', 'ArsipStatisController@index')->name('index');
            Route::get('/get', 'ArsipStatisController@get')->name('get');
            Route::get('/create', 'ArsipStatisController@create')->name('create');
            Route::get('/{id}', 'ArsipStatisController@show')->name('show');
            Route::post('/store', 'ArsipStatisController@store')->name('store');
            Route::post('/update/{id}', 'ArsipStatisController@update')->name('update');
            Route::post('/delete', 'ArsipStatisController@destroy')->name('destroy');
        });
        Route::group([], function () {
            Route::get('/', 'AkuisisiController@index')->name('index');
            Route::get('/get', 'AkuisisiController@getList')->name('get');
            Route::get('/create', 'AkuisisiController@create')->name('create');
            Route::get('/{id}', 'AkuisisiController@show')->name('show');
            Route::post('/store', 'AkuisisiController@store')->name('store');
            Route::post('/confirm', 'AkuisisiController@confirm')->name('confirm');
            Route::post('/update/{id}', 'AkuisisiController@update')->name('update');
            Route::post('/delete', 'AkuisisiController@destroy')->name('destroy');
        });
    });
});

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

app/Http/Controllers/AkuisisiController.php
<?php

namespace App\Http\Controllers;

use App\Constants\StatusAkuisisi;
use App\Lembaga;
use App\Model\Akuisisi;
use App\Model\AkuisisiBeritaAcara;
use App\Model\AkuisisiTimPenilai;
use App\Services\Auth;
use App\Traits\ConsumeSrikandi;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use NcJoes\OfficeConverter\OfficeConverter;
use PhpOffice\PhpWord\TemplateProcessor;

class AkuisisiController extends Controller
{
    use ConsumeSrikandi;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        /*$response = $this->performRequest('GET', '/api/berkas');

        $data = [];
        foreach ($response['data'] as $key => $item) {
            $data[] = $item;
        }*/

        return view('pages.akuisisi.akuisisi.index');
    }

    public function getList(Request $request)
    {
        $http_query = http_build_query($request->all());
        $response = $this->performRequest('GET', '/api/berkas' . ($http_query ? '?' . $http_query : ''));

        $data = [];
        foreach ($response['data'] as $key => $item) {
            $items = AkuisisiTimPenilai::query()->where('berkas_id', $item->id)->get();
            $item->team = $items;

            $data[] = $item;
        }

        return response()->json(compact(['data']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\JsonResponse|Response
     */
    public function store(Request $request)
    {
        $rules = [
            'ketua' => 'required',
            'anggota' => 'required',
        ];

        $ruleMessages = [
            'ketua.required' => 'ketua harus diisi',
            'anggota.*.required' => 'anggota wajib diisi',
        ];

        $validator = Validator::make($request->all(), $rules, $ruleMessages);

        if ($validator->fails()) {
            $errors = $validator->errors()->all();
            $htmlErrors = '<ul>';

            foreach ($errors as $item) {
                $htmlErrors .= '<li>' . $item . '</li>';
            }

            $htmlErrors .= '</ul>';

            return response()->json([
                'code' => Response::HTTP_OK,
                'status' => false,
                'error' => $validator->errors()->all(),
                'message' => '<div class="alert alert-danger">Mohon masukkan data yang sesuai dengan formulir:<br>' . $htmlErrors . '</div>'
            ]);
        }

        DB::beginTransaction();

        try {
            $data_insert = [];
            foreach ($request->anggota as $key => $item) {
                if ($key == 0)
                    $data_insert[] = [
                        'berkas_id' => $request->berkas_id,
                        'user_id' => $request->ketua,
                        'role' => 'ketua',
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                    ];

                $data_insert[] = [
                    'berkas_id' => $request->berkas_id,
                    'user_id' => $item,
                    'role' => 'anggota',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ];
            }

            AkuisisiTimPenilai::query()->insert($data_insert);

            DB::commit();

            return response()->json([
                'code' => Response::HTTP_OK,
                'status' => true,
                'message' => '<div class="alert alert-success">Data berhasil disimpan</div>'
            ]);
        } catch (\Exception $e) {
            DB::rollback();
            Log::error($e);

            return response()->json([
                'code' => Response::HTTP_INTERNAL_SERVER_ERROR,
                'status' => false,
                'message' => '<div class="alert alert-danger">Data gagal disimpan</div>'
            ]);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\JsonResponse|Response
     */
    public function confirm(Request $request)
    {
        $rules = [
            'kode_klasifikasi' => 'required',
            'berkas' => 'required|array',
            'penerima' => 'required',
        ];

        $ruleMessages = [
            'kode_klasifikasi.required' => 'kode klasifikasi harus diisi',
            'berkas.required' => 'berkas wajib diisi',
            'penerima.required' => 'penerima harus diisi',
        ];

        $validator = Validator::make($request->all(), $rules, $ruleMessages);

        if ($validator->fails()) {
            $errors = $validator->errors()->all();
            $htmlErrors = '<ul>';

            foreach ($errors as $item) {
                $htmlErrors .= '<li>' . $item . '</li>';
            }

            $htmlErrors .= '</ul>';

            return response()->json([
                'code' => Response::HTTP_OK,
                'status' => false,
                'error' => $validator->errors()->all(),
                'message' => '<div class="alert alert-danger">Mohon masukkan data yang sesuai dengan formulir:<br>' . $htmlErrors . '</div>'
            ]);
        }

        DB::beginTransaction();

        try {
            $count_ba = AkuisisiBeritaAcara::query()->count();
            $ba_code = $request->kode_klasifikasi . '/' . sprintf("%03d", ($count_ba + 1)) . '/' . Carbon::now()->format('Y');

            $template_ba = "public/templates/berita-acara.docx";

            $file_directory = storage_path() . '/app/public/berita-acara/';
            if (!file_exists($file_directory))
                mkdir($file_directory, 0777);

            $file_name = time() . '' . sprintf("%05d", random_int(0, 1000));
            $file_name_docx = $file_name . '.docx';
            $file_name_pdf = $file_name . '.pdf';

            $template = new TemplateProcessor(storage_path('app/' . $template_ba));
            $template->setValue('nomor_berita_acara', $ba_code);
            $template->saveAs($file_directory . $file_name_docx);
            $exec = 'et HOME=/tmp && soffice --headless --convert-to pdf "C:\xampp\htdocs\siks\storage\app\public\berita-acara\163654053700169.docx" --outdir "C:\xampp\htdocs\siks\storage\app\public\berita-acara';
            dd();

            $converter = new OfficeConverter($file_directory . $file_name_docx, $file_directory, 'soffice');
            $converter->convertTo($file_name_pdf);

            Storage::disk('local')->delete('public/berita-acara/' . $file_name_docx);

            $ba = new AkuisisiBeritaAcara();
            $ba->kode_klasifikasi = $request->kode_klasifikasi;
            $ba->penerima_id = $request->penerima;
            $ba->nama_penerima = $request->penerima;
            $ba->nomor = $ba_code;
            $ba->file_name = $file_name_pdf;
            $ba->file_path = 'app/public/berita-acara/' . $file_name_pdf;
            $ba->created_by = Auth::user()->username;
            $ba->save();

            $data_insert_head = [];
            foreach ($request->berkas as $key => $item) {
                $data_insert_head[] = [
                    'kode_klasifikasi' => $request->kode_klasifikasi,
                    'berkas_id' => $item['berkas_id'],
                    'berita_acara_id' => $ba->id,
                    'penerima_id' => $request->penerima,
                    'nama_penerima' => $request->penerima,
                    'nama_berkas' => $item['nama_berkas'],
                    'kurun' => $item['kurun'],
                    'status' => StatusAkuisisi::SELESAI_AKUISISI,
                    'sifat' => $item['sifat'],
                    'status_arsip' => $item['status_arsip'],
                    'data' => $item['data'],
                    'created_by' => Auth::user()->username,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ];
            }

            Akuisisi::query()->insert($data_insert_head);

            /* todo: save item akuisisi */

            DB::commit();

            return response()->json([
                'code' => Response::HTTP_OK,
                'status' => true,
                'message' => '<div class="alert alert-success">Data berhasil disimpan</div>',
                'data' => [
                    'bapp_code' => $ba_code
                ]
            ]);
        } catch (\Exception $e) {
            DB::rollback();
            Log::error($e);

            return response()->json([
                'code' => Response::HTTP_INTERNAL_SERVER_ERROR,
                'status' => false,
                'message' => '<div class="alert alert-danger">Data gagal disimpan</div>'
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $data = (object)[
            'id' => $id,
            'kode_klasifikasi' => 'LK.02',
            'desc' => 'Berkas Pengajuan Dupak a.n Meri Andriani',
            'penyusutan_akhir' => 'Permanen',
            'lokasi' => 'Gedung ANRI',
            'tahun' => 2023,
            'jumlah' => 2,
            'jra_aktif' => Carbon::now()->addMonth(11)->addYear(1)->format('d M Y'),
        ];

        $berkas = [
            (object)[
                'id' => rand(),
                'kode_klasifikasi' => 'Masuk',
                'desc' => 'D1.01.02/1/2021',

resources/views/pages/akuisisi/usul_serah/index.blade.php
@extends('layouts.begin_back')

@section('open_akuisisi', 'nav-item-expanded nav-item-open')

@section('akuisisi', 'active')

@section('akuisisi_usul-serah_index', 'active')

@section('title', 'Arsip Usul Serah')

@section('content')
    <!-- Page header -->
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4>
                <i class="icon-drawer-in mr-2"></i> <span class="font-weight-semibold">Arsip Usul Serah</span> - List
            </h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        {{--<div class="header-elements d-none text-center text-md-left mb-3 mb-md-0">
            <a href="{{route('akuisisi.usul-serah.create')}}"
               class="btn bg-teal btn-labeled btn-labeled-left">
                <b><i class="icon-plus2"></i></b> Buat baru
            </a>
        </div>--}}
    </div>
    <!-- /page header -->


    <div class="page-content pt-0">
        <div class="content-wrapper">
            <div class="content">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-header bg-white">
                                <h6 class="card-title">Arsip Usul Serah</h6>
                            </div>
                            <table class="table datatable-responsive-control-right table-hover table-bordered">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Kode Klasifikasi</th>
                                    <th style="width: 20%">Uraian Arsip</th>
                                    <th style="width: 40%">Kurun Waktu</th>
                                    <th>Jumlah Arsip</th>
                                    <th style="width: 30%">Akhir Retensi Arsip</th>
                                    <th style="width: 20%" class="text-center">Aksi</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                
                                @foreach ($data as $key => $item)
                                    <tr>
                                        <td>{{ $key + 1 }}</td>
                                        <td>{{ $item->klasifikasi->kode }}</td>
                                        <td>{{ $item->nama }}</td>
                                        <td>{{ $item->kurun }}</td>
                                        <td>{{ $item->jumlah }}</td>
                                        <td>{{ \Carbon\Carbon::parse($item->tanggal_tutup)->format('d M Y') }}</td>
                                        <td style="white-space: nowrap">
                                            <a href="{{ route('akuisisi.usul-serah.show', ['id' => $item->id]) }}"
                                               class="list-icons-item text-info btn-icon">
                                                <i class="icon-file-eye"></i>
                                            </a>
                                        </td>
                                        <td></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('addon-script')
    <script src="{{ asset('global_assets/js/plugins/notifications/sweet_alert.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/tables/datatables/extensions/responsive.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/forms/styling/switchery.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/forms/styling/switch.min.js') }}"></script>
@endpush

@section('footer-script')
    <script src="{{ asset('global_assets/js/demo_pages/datatables_responsive.js') }}"></script>
    <script src="{{ asset('global_assets/js/demo_pages/form_checkboxes_radios.js') }}"></script>

    <script>
        $(document).ready(function () {
            $('.datatable-responsive-control-right').on('click', '.delete-item', function (e) {
                var id = $(this).data('id');

                swal.fire({
                    title: 'Hapus Arsip Usul Serah',
                    text: 'Apakah Anda yakin ingin menghapus Arsip Usul Serah ini?',
                    type: 'question',
                    showCancelButton: true,
                    confirmButtonText: 'Ya, Hapus!',
                    cancelButtonText: 'Batal!',
                    confirmButtonClass: 'btn btn-danger',
                    cancelButtonClass: 'btn btn-link',
                    buttonsStyling: false
                }).then(function (result) {
                    if (result.value) {
                        $.ajax({
                            method: 'POST',
                            dataType: 'json',
                            url: "{{ route('akuisisi.usul-serah.destroy') }}",
                            data: {
                                "_token": "{{ csrf_token() }}",
                                "id": id,
                            }
                        }).done(function (response) {
                            if (response.status == true) {
                                swal.fire({
                                    title: 'Yeay!',
                                    text: response.message,
                                    type: 'success'
                                });
                                location.reload();
                            } else if (response.status == false) {
                                swal.fire({
                                    title: 'Auch!',
                                    text: response.message,
                                    type: 'error'
                                });
                                location.reload();
                            }
                        })
                    }
                });
            });

            $('.dataTables_length select').select2({
                minimumResultsForSearch: Infinity,
                dropdownAutoWidth: true,
                width: 'auto'
            });
        });

        function initDatatable() {
            $('.datatable-responsive-control-right').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('akuisisi.usul-serah.get') }}",
                columns: [
                    {
                        "data": "nomenklatur_ori"
                    },
                    {
                        "data": "nama"
                    },
                    {
                        "data": "status"
                    },
                    {
                        // "data": 'action',
                        "name": 'action',
                        "orderable": false,
                        "searchable": false
                    },
                    {
                        "data": null,
                        "defaultContent": ""
                    },
                ],
                responsive: {
                    details: {
                        type: 'column',
                        target: -1
                    }
                },
                columnDefs: [
                    {
                        "className": "dt-body-center",
                        "targets": [3],
                        "render": function (data, type, row) {
                            let id = row['id'];
                            return '<a href="/unit-kerja/' + id + '/edit" class="list-icons-item text-info btn-icon">' +
                                '   <i class="icon-pencil"></i>' +
                                '</a>' +
                                '   <a href="#" data-id="' + id + '" class="list-icons-item text-danger btn-icon delete-item">' +
                                '   <i class="icon-trash"></i>' +
                                '</a>';
                        }
                    },
                    {
                        className: 'control',
                        orderable: false,
                        targets: -1
                    },
                    {
                        width: "100px",
                    },
                    {
                        orderable: false,
                    }
                ]
            });
        }
    </script>
@endsection